### ISSUE TITLE
Maybe have Pause and Step Forward buttons as well as plate size and distance arrows visible through light?

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/capacitor-lab-basics#276] opened 2020-10-16 21:23 UTC
For https://github.com/phetsims/QA/issues/565

While checking another issue, I noticed it is difficult to adjust the plate size and distance as well as pause, unpause, or stepforward while the light is shining. Some arrows are visible through light but are not the ones which can be manipulated.

Currently how the screen looks while paused and the light is shining. 

![2020-10-16CapacitorlabbasicsLightOverArrows](https://user-images.githubusercontent.com/54685448/96309900-77548800-0fc3-11eb-9707-b0870e0b66da.PNG)

**Comment by Denz1994** [comment] 2020-10-17 20:25
I agree we should be consistent with the arrow layering. @arouinfar Do you think we should have all the arrows behind the light or in front of the light? I personally think the light should be blocking the arrows. Almost as if the user is blinded by the light and can't see the arrows behind it.

**Comment by arouinfar** [comment] 2020-10-22 02:54
I think this should be addressed by reducing the maximum halo size in #275.

@Denz1994 I think it looks strange to have mixed layering. Let's put the light on top of everything. I think they only z-order you'll need to adjust is the current arrows.

**Comment by KatieWoe** [comment] 2020-10-28 21:16
I was writing this up as a bug since it makes using the sim difficult.
**Problem description**
For https://github.com/phetsims/QA/issues/565. Mentioned in https://github.com/phetsims/capacitor-lab-basics/issues/256. Related to and possibly caused by changes in https://github.com/phetsims/capacitor-lab-basics/issues/270.
On the Light Bulb screen, if the light from the bulb is big enough, it covers the play/pause, step forward, and speed control buttons. This makes using the controls in fairly normal circumstances difficult.
![lightlayer](https://user-images.githubusercontent.com/41024075/97497721-91ca2200-1930-11eb-92a3-dfb561da3b06.gif)

**Comment by Denz1994** [comment] 2020-10-29 02:48
Seems like @KatieWoe is advocating for the light being behind interactable items? I didn't think about the paused state, but I must admit it does get annoying to have to "feel" around for the step button when the light blocks the play/pause panel.

Maybe move the current direction arrows behind the light and the play/pause button in front of it @arouinfar?

**Comment by Denz1994** [comment] 2020-11-11 04:38
The rendering order of the lightbulb and current arrows has been changed. The arrows are now always behind the lightbulb halos. Will deploy an RC version for verification.

**Comment by DevonQui** [comment] 2020-12-17 21:30
The problem has definitely improved though I did find a case where the light will still be too bright to see the pause and play buttons. I think it's a pretty rare case to run into unless you're really trying to play with every button in the simulation but I thought it was important to note nonetheless.[
<img width="1440" alt="Screen Shot 2020-12-17 at 2 26 11 PM" src="https://user-images.githubusercontent.com/72042459/102546163-764bdf80-4074-11eb-8fac-0c4805f16192.png">
](url)

**Comment by brooklynlash** [comment] 2020-12-21 19:29
I noticed this as well, and only occurs when the separation is low and the plate area is high when originally charging the capacitor, then taking it off the voltage and increasing separation/decreasing plate area. You cannot make it so the light is covering the pause/step forward buttons with the original charge without changing the plates.

**Comment by KatieWoe** [comment] 2021-01-14 20:20
I made a gif of how this can be fairly easily achieved. Fully charge the plates when they are large and close together. Disconnect the plates but don't connect them to the light bulb. Make the plates small and far apart. Pause the sim. Connect them to the light bulb.
![howtocoverbuttons](https://user-images.githubusercontent.com/41024075/104644407-f9a82300-566a-11eb-8496-aa5994740ef1.gif)

**Comment by arouinfar** [comment] 2021-01-15 01:19
@Denz1994 let's move the panel containing the TimeControlNode on top of the halo. This z-ordering would be consistent with the other panels in the sim.

**Comment by jonathanolson** [comment] 2021-02-02 04:11
I believe I've fixed this in master, can you check? (Not committed to 1.7)

**Comment by brooklynlash** [comment] 2021-02-02 16:42
I was trying to replicate https://github.com/phetsims/capacitor-lab-basics/issues/276#issuecomment-760452899 but ran into another problem, when I change the separation or plate size at all, the energy disappears. @arouinfar is this intended?
![capacitorenergy](https://user-images.githubusercontent.com/72031637/106632386-eb974500-653a-11eb-84d1-5c426b01cff3.gif)

**Comment by jonathanolson** [comment] 2021-02-02 17:09
I discovered this and reported in https://github.com/phetsims/capacitor-lab-basics/issues/282.

I'll investigate

**Comment by arouinfar** [comment] 2021-02-03 04:58
@jonathanolson looks good in master, back to you in case we end up needing to cherry-pick into 1.7.

**Comment by KatieWoe** [comment] 2021-03-25 16:49
Looks like this in https://github.com/phetsims/QA/issues/616:
<img width="951" alt="looksindev" src="https://user-images.githubusercontent.com/41024075/112511127-b8fa1380-8d57-11eb-8760-e3cc1578ddc8.png">
@arouinfar I think this can be closed?

**Comment by arouinfar** [comment] 2021-03-25 21:51
Since we decided to republish off of master, there shouldn't be anything to cherry-pick, closing.

**Closed by arouinfar** 2021-03-25 21:51 UTC
Labels: status:ready-for-qa, type:suggestion
