### ISSUE TITLE
Stopwatch always pulled to front even if voltmeter is grabbed

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/capacitor-lab-basics#279] opened 2021-01-13 16:29 UTC
**Test device**
Lenovo ThinkPad

**Operating System**
Windows10

**Browser**
Chrome, Firefox

**Problem description**
In the "Light" section, both the stopwatch and voltmeter can be grabbed, but even if you grab and drag around the voltmeter, it will not pop to the front. 

**Visuals**
![capacitorstopwatch](https://user-images.githubusercontent.com/72031637/104480406-c6d63000-5581-11eb-94ec-da654180e262.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.8/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.8 2020-12-17 01:25:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment] 2021-01-15 01:15
This is a duplicate of #280, closing.

**Closed by arouinfar** 2021-01-15 01:15 UTC
Labels: type:bug
