### ISSUE TITLE
Voltmeter can be dragged off screen

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/capacitor-lab-basics#62] opened 2016-04-20 18:33 UTC
The voltmeter can be pulled out of the screen and if you let go of it, it can't be recovered without refreshing. 
![screen shot 2016-04-20 at 12 29 07 pm](https://cloud.githubusercontent.com/assets/11947677/14685922/dcbb337a-06f3-11e6-942b-970371151a29.png)

Related to phetsims/tasks#575

**Comment by jessegreenberg** [comment] 2016-04-20 18:36
Thanks @brroberts1231.  The voltmeter should use MovableDragHandler to restrict the dragging to the bounds of the simulation.  By 'refreshing' do you mean 'resetting' the simulation?  Does pressing the reset button not put the voltmeter back in the toolbox?

**Comment by brroberts1231** [comment] 2016-04-20 18:41
Reset button does work.

**Comment by jessegreenberg** [comment] 2016-04-20 18:46
Sorry! Misread the comment to 'it can't be recovered with refreshing'.  Thanks, reassigning to me.

**Comment by jessegreenberg** [comment] 2016-04-21 15:20
@andrewadare would you mind taking a look at this issue?  We will need to replace the voltmeter drag handler with MovableDragHandler and user the screen view layout bounds to restrict the dragging of the voltmeter body.

**Comment by jessegreenberg** [comment] 2016-04-21 15:20
Actually, we will need to do this for the probes as well, I am sure they suffer from the same issue.

**Comment by andrewadare** [comment] 2016-04-22 19:16
In VoltMeterBodyNode, the drag handler is already a MovableDragHandler, but something looks suspicious: the dragBounds are set to something like the layout boundaries in view coordinates (0,0,1024,618), but it's observing `voltmeter.bodyLocationProperty`, which is specified in model coordinates (~1e-2 meters).

**Comment by andrewadare** [comment] 2016-04-22 19:28
The JSDoc for the Voltmeter constructor says it takes a ModelViewTransform2, but it appears to be taking a CLBModelViewTransform3D. I assume that's a doc problem, and not a bug in the code?

**Comment by andrewadare** [comment] 2016-04-22 19:40
It is unexpected to me that CapacitanceModel and CLBLightBulbModel are setting
```
this.worldBounds = CLBConstants.CANVAS_RENDERING_SIZE.toBounds(); // @private
```
I would think that there should be a view-to-model transformation. 

I'd like to quickly test this, but unfortunately there's no modelToViewBounds in CLBModelViewTransform3D.

**Comment by andrewadare** [comment] 2016-04-22 19:49
I can confirm that putting in some rough numbers like
```
this.worldBounds = new Bounds2(0, 0, 0.07, 0.04);
```
in CapacitanceModel prevents dragging outside the area (but then causes other problems)

**Comment by jessegreenberg** [comment] 2016-04-22 22:42
Ah, good points @andrewadare!  The use of CLBModelViewTransform3D is probably what prevented traditional use of MovableDragHandler in the first place.  But the bounds are two dimensional, so perhaps we can add a 2D bounds transform to CLBModelViewTransform3D.

**Comment by jessegreenberg** [comment] 2016-04-22 23:31
This was tricky because MovableDragHandler is tailored to work with Vector2.

**Comment by jessegreenberg** [comment] 2016-04-22 23:41
Commit above is working nicely, but the voltmeter can still be dragged too far down.

**Comment by jessegreenberg** [comment] 2016-04-22 23:53
Image shows that the image bounds are a bit dilated around the actual image.  Also, it looks like MovableDragHandler restricts dragging to the *top* of the node.  For this situation, we want the drag bounds to be adjusted by the height of the image.

![imagebounds](https://cloud.githubusercontent.com/assets/6396244/14757637/da8b5056-08b2-11e6-8245-b4608a40f1dc.PNG)

**Comment by jessegreenberg** [comment] 2016-04-22 23:56
Same issue to the right edge of the view bounds.

**Comment by jessegreenberg** [comment] 2016-04-23 00:15
This does not restrict the voltmeter if it has been dragged out from the toolbox, since the toolbox implements its own drag handler.  It would be better if on ```down``` the toolbox could initiate the startDrag of the voltmeter movable drag handler.

**Comment by jessegreenberg** [comment] 2016-04-23 00:24
The ToolBoxPanel also uses this:

```
        if ( !parentScreenView ) {
          // find the root parent screenView
          var testNode = thisToolBoxPanel;
          while ( testNode !== null ) {
            if ( testNode instanceof ScreenView ) {
              parentScreenView = testNode;
              break;
            }
            testNode = testNode.parents[ 0 ]; // Move up the scene graph by one level
          }
          assert && assert( parentScreenView, 'unable to find parent screen view' );
        }
```

and it is recommended to avoid this pattern.

**Comment by jessegreenberg** [comment] 2016-04-23 00:33
I also notice that the voltmeter is added back in to the panel with this block, which is duplicated in each screen view.

    // track user control of the voltmeter and place the voltmeter back in the tool box if bounds collide.
    model.voltmeter.inUserControlProperty.link( function( inUserControl ) {
      if ( !inUserControl && voltmeterToolbox.bounds.intersectsBounds( voltmeterNode.bodyNode.bounds.eroded( 40 ) ) ) {
        model.voltmeterVisibleProperty.set( false );
      }
    } );

It would be best if this were in VoltmeterToolBoxNode.

**Comment by jessegreenberg** [comment] 2016-04-23 15:08
Above commit fixes https://github.com/phetsims/capacitor-lab-basics/issues/62#issuecomment-213634766.

**Comment by jessegreenberg** [comment] 2016-04-23 15:13
Above commit fixes https://github.com/phetsims/capacitor-lab-basics/issues/62#issuecomment-213635460.

**Comment by jessegreenberg** [comment] 2016-04-23 15:25
The solution to https://github.com/phetsims/capacitor-lab-basics/issues/62#issuecomment-213624322 uses ```constructor.name``` to identify Vector2, but I just noticed that Vector2 has an isVector2 property and it would be better to use this.

**Comment by andrewadare** [comment] 2016-04-25 15:41
Well, this issue ended up leading to quite a number of code improvements. Drag behavior looks good to me now. This is ready for re-testing.

**Comment by andrewadare** [comment] 2016-04-25 15:51
Actually, there is now one annoyance: the voltmeter probe tip cannot contact the lowest segment of the circuit. We need to decide what's best.
1. Leave it as is (probably not)
2. Extend the lower y-boundary (adds empty space & effectively shrinks the whole view)
3. Allow the probe to go partially out of view at the bottom
4. Shift up the whole circuit a little
5. Some minimally-disruptive combination of 2,3,4.

**Comment by andrewadare** [comment] 2016-04-25 16:01
I went with option 3 for now,  because it was a 2 byte change (ok, more with whitespace) and it doesn't disrupt the layout like the other options.

Note that this is not a new problem.

**Comment by jessegreenberg** [comment] 2016-04-25 16:06
:+1: Option 3 would be my vote as well, as long as the probe cannot get lost at the beyond the bottom of the screen, that sounds good to me.

**Closed** 2016-05-13 21:42 UTC
Labels: status:fixed-pending-testing
