### ISSUE TITLE
Assertion failed: invalid value

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#188] opened 2017-09-19 19:50 UTC
```
Error: Assertion failed: invalid value: 3.255195758482075e-12
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/assert/js/assert.js:22:13)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/axon/js/Property.js?bust=1505834855811:138:40)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/capacitor-lab-basics/js/common/model/circuit/ParallelCircuit.js?bust=1505834855811:204:46)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/axon/js/Emitter.js?bust=1505834855811:206:49)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/axon/js/Property.js?bust=1505834855811:204:29)
    at Property._setAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/axon/js/Property.js?bust=1505834855811:193:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/axon/js/Property.js?bust=1505834855811:140:16)
    at end (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/capacitor-lab-basics/js/common/view/drag/CircuitSwitchDragHandler.js?bust=1505834855811:143:49)
    at CircuitSwitchDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/scenery/js/input/SimpleDragHandler.js?bust=1505834855811:205:26)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1505828258581/scenery/js/input/SimpleDragHandler.js?bust=1505834855811:93:16)
```

**Comment by jonathanolson** [comment] 2017-10-12 03:32
![capacitor-over](https://user-images.githubusercontent.com/480878/31478053-cfc19cc4-aeca-11e7-83ce-1243971d6ba1.PNG)

This looks like it can happen naturally when (potentially?) the light-bulb hits large amounts of energy. For the above shot, I took away the (dominating) light bulb light.

**Comment by jonathanolson** [comment] 2017-10-12 03:33
Removed the cause above, closing.

**Closed by jonathanolson** 2017-10-12 03:33 UTC
Labels: type:automated-testing, type:bug
