### ISSUE TITLE
Current arrows not visible when re-charging capacitor

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#130] opened 2016-08-02 23:21 UTC
Observed in dev.27 (and master) on latest OSX/Chrome. 

Steps to reproduce
* Charge capacitor, switch to bulb
* Let bulb drain the capacitor completely
* Switch back to battery, current arrows do not appear when recharging (unless switch first travels through middle position) 

![currentarrows](https://cloud.githubusercontent.com/assets/8419308/17348564/3127a04c-58d4-11e6-9965-dc2c9da70b24.gif)

**Comment by andrewadare** [comment] 2016-09-21 23:21
Spent quite a bit of time trying to track this down today. Some notes:

* AbstractCircuit [updates the plate voltage](https://github.com/phetsims/capacitor-lab-basics/blob/9fe4d1ed8d508f6ad97536162069cc33093d823d/js/common/model/circuit/AbstractCircuit.js#L115) when the circuit connection changes, but it does not update the current there also.
* The current gets updated every time step (see updateCurrentAmplitude(dt), also in AbstractCircuit.js)
* The switching from the light-bulb branch to the battery branch occurs at time step k. The circuitConnection property gets assigned BATTERY_CONNECTED. updatePlateVoltage gets called twice before the next timestep. In the first call, the plate voltage and charge rise sharply. In the second, they don't change at all, because the capacitor is already at the full battery voltage.
* Since updateCurrentAmplitude uses dQ/dt in BATTERY_CONNECTED mode, the current is computed as zero since dQ is zero.

So, the current update is being missed while the charge is actually changing. That's the problem. Solutions?
* remove one call to updateVoltage
* somehow insert a call to updateCurrentAmplitude

Not sure about side effects, or which would be best,

**Comment by andrewadare** [comment] 2016-09-23 17:13
While debugging, I tried adding a call to updateCurrentAmplitude here (in AbstractCircuit):
```js
    // Whenever a circuit property changes, all segments are updated. This works, but is excessive.  If there are
    // performance issues, these links would be a great place to start.
    // udpate all segments, disconnected plate charge, and plate voltages when the connection property changes
    this.circuitConnectionProperty.lazyLink( function( circuitConnection ) {
      /*
       * When disconnecting the battery, set the disconnected plate charge to whatever the total plate charge was with
       * the battery connected.  Need to do this before changing the plate voltages property.
       */
      if ( circuitConnection !== CircuitConnectionEnum.BATTERY_CONNECTED ) {
        self.setDisconnectedPlateCharge( self.getTotalCharge() );
      } else {
        // #130 Need to also call updateCurrentAmplitude() here?
        self.updateCurrentAmplitude(1/60); // DEBUG ONLY
      }
      self.updatePlateVoltages();

      updateSegments( circuitConnection );
    } );

```
It does the right thing for the battery branch (the arrows are displayed while the capacitor charges), but the light bulb branch also shows the current indicator arrows, even though the light bulb is disconnected.

The troubling part of this bug is that everything works properly if the capacitor is not fully discharged when it is switched back over to the battery. That is still not understood yet.

**Comment by andrewadare** [comment] 2016-09-23 17:40
As an aside, there's an undesirable mixture of implementation and delegation in AbstractCircuit.js. Seems like an abstract class should be just that--delegation to descendants only, serving as a uniform interface. Functions like getStoredEnergy, updateCurrentAmplitude, and getPlatesDielectricFieldAt are carrying out implementations, while updatePlateVoltages explicitly delegates to descendants. 

This doesn't help with trying to figure out the source of this problem. I may need to overhaul this to make things more uniform and organized.

**Comment by andrewadare** [comment] 2016-09-26 16:25
Evidently, this line in LightBulbCircuit is enough to fix this:
```js
          this.previousTotalCharge = 0; // This fixes #130
```
 This way, updateCurrentAmplitude in AbstractCircuit is able to compute a nonzero dQ/dt when the switch is thrown back to the battery branch, and the arrows appear.

I'm speculating (since I haven't reproduced it), but this may have a favorable influence on the "current oscillation" bug #125.

**Comment by phet-steele** [comment] 2016-10-05 18:01
@andrewadare I cannot repro this with a mouse, but I can with touch. In the last step above, while switching to the battery, if I touch and hold on the switch position, I often do not see current arrows. I believe this is caused by two things. 

1) The sim immediately starts a drag event on the switch pin once my finger touches the switch position.
2) Since I'm dragging the switch pin, the circuit is technically open. Therefore no current can be seen for more than a blink of an eye. See #140 and the first part of https://github.com/phetsims/capacitor-lab-basics/issues/119#issuecomment-228173027 for how the sim handles dragging the switch.

**Comment by andrewadare** [comment] 2016-10-11 17:43
Hopefully increasing the minimum battery voltage for https://github.com/phetsims/capacitor-lab-basics/issues/138 also helps here.

Otherwise, in order to come up with a fix, I will need a more specific description of the problem than this:

> @andrewadare I cannot repro this with a mouse, but I can with touch. In the last step above, while switching to the battery, if I touch and hold on the switch position, I often do not see current arrows. I 

I'm going to defer this issue to the next testing round to see if it's still a problem. If so, please note it here.

**Comment by phet-steele** [comment] 2016-10-21 16:27
@andrewadare this was still an issue on touch devices in 1.0.0-dev.29. As I say above:

> if I touch and hold on the switch position, I often do not see current arrows

This has been traced to touchSnag starting a drag event immediately after selecting a connection point. So, for a blink of an eye, the circuit is closed and the plates become charged. Then a drag starts and the sim believes that the circuit is open, therefore not showing any current arrows.

The plates will recharge with no accompanying current arrows (don't need to hold for as long as I did in the video):
![clb07](https://cloud.githubusercontent.com/assets/5863899/19605619/b66cf152-9778-11e6-8491-b265e29ca9ed.gif)

As a "quick fix", disabling touchSnag for the switch does solve the problem (in the branch: no-touchsnag). The trade-off, more precise touching required to interact, may not be optimal. Myself, @arouinfar, and @ariel-phet still felt that the sim was usable. The wire section of the switch became very difficult to touch, but the tip/solder ball was still easily usable.

@andrewadare I think we can go ahead and merge the changes from the no-touchsnag branch (it's just a one line change anyway). There is one last design request from @ariel-phet that I will write in another issue.

Just in case we renege:
There is another option that can be taken that involves more time, but keeps touchSnag in place. The idea was to temporarily disable pickability of the switch after a connection point is chosen, then re-enable pickability once the finger has left the screen.

**Comment by andrewadare** [comment] 2016-10-21 20:04
@phet-steele @jessegreenberg I "merged" this change to master. Thanks for identifying the issue. To tag this as a potentially-resolved issue, I'm going to mark as "ready to test" even though you've tested on the no-touchsnag branch already.

**Comment by phet-steele** [comment] 2016-10-25 18:09
These changes are working nicely for me, closing. Thanks @andrewadare and @jessegreenberg!

**Closed by phet-steele** 2016-10-25 18:09 UTC
Labels: status:ready-to-test, type:bug
