### ISSUE TITLE
some labels move and change quality when the voltmeter or peaks move over labels. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/capacitor-lab-basics#232] opened 2018-02-14 18:30 UTC
Test device: MacBook Air

Operating System: macOS High Sierra version 10.13.2

Browser: Chrome Version 64.0.3282.167 

Problem description:  when the voltmeter or the peaks move over the labels, some of them move and they change to less quality font. 

Steps to reproduce:
1) Open the sim 
2) select Capacitance view 
3) take out the voltmeter of it box 
4) drag the voltmeter and move it over the control boxes 
5) pay attention to the labels, in special the values in the plates, but some other labels in the control boxes can move too. 

Screenshots:
![untitled](https://user-images.githubusercontent.com/26031501/36220968-c039d444-1179-11e8-8fe8-206ffbdcadec.gif)
phetsims/QA/issues/94

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_all_phet.html
Version: 1.6.6-rc.1 2018-02-02 17:56:34 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Language: en-US
Window: 1440x697
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"e1350857","branch":"HEAD"},"brand":{"sha":"53cf227b","branch":"HEAD"},"capacitor-lab-basics":{"sha":"8cd25a5a","branch":"HEAD"},"chipper":{"sha":"3bd83184","branch":"HEAD"},"dot":{"sha":"8d471f40","branch":"HEAD"},"joist":{"sha":"caefa8e2","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"626f2c93","branch":"HEAD"},"phet-io-website":{"sha":"766da99e","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrapper-sonification":{"sha":"a3d5056c","branch":"HEAD"},"phet-io-wrapper-visualizing-engagement":{"sha":"83ca1fe3","branch":"HEAD"},"phet-io-wrappers":{"sha":"eb4b33ba","branch":"HEAD"},"phetcommon":{"sha":"d33be800","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"scenery":{"sha":"70cf829b","branch":"HEAD"},"scenery-phet":{"sha":"42b94b4f","branch":"HEAD"},"sherpa":{"sha":"d59690f0","branch":"HEAD"},"sun":{"sha":"3b4ff6c4","branch":"HEAD"},"tandem":{"sha":"4de02ea3","branch":"HEAD"},"twixt":{"sha":"83e1f948","branch":"HEAD"}}

**Comment by DianaTavares** [comment] 2018-02-14 18:57
Probably part of the same problem, 

Description: in the "Light Bulb" view, when the capacitor is discharging connected to the bulb, the label "Stored Energy" shakes. 

Steps to reproduce: 
1) Open the sim in the "Light Bulb" view
2) move the voltage in the battery to 1.5 V 
3) Change the plate separation to the minimum value, and the plate area to the maximum 
3) connect the capacitor to the bulb 
4) pay attention to the "Stored Energy" label, it will shake almost in the end of the discharge 
5) the label "Stored Energy" always shake when the capacitor is discharging with the bulb, but in this example is more evident because the discharge is for long time.

Screenshots:
![untitled](https://user-images.githubusercontent.com/26031501/36222257-0f4d5c14-117e-11e8-877c-825b3dac441b.gif)

**Comment by phet-steele** [comment] 2018-02-15 20:24
@jonathanolson @DianaTavares I also cannot reproduce with the same OS + browser setup. My guess is this is a hardware issue? @jonathanolson what would you like to do with this issue?

**Comment by jonathanolson** [comment] 2018-02-15 22:06
I'm curious why it's happening. May be related to the pixel ratio of the display (so testing on similar hardware, if available may be nice, but not sure if it's worth the time). Additionally, I'd want to verify that the browser has a default zoom (100%), and I'd be curious about any plugins or non-default settings that may be causing this.

@ariel-phet, presumably up to you what priority this would be at.

**Comment by ariel-phet** [comment] 2018-02-16 02:03
Check with @DianaTavares - only happening on Chrome, and verified browser set to default zoom.

Since this appears to be hardware specific and it is aesthetically displeasing (but not egregious). Also this will cause no pedagogical issues. marking as "won't fix"

**Comment by arouinfar** [comment] 2020-10-14 23:52
I can reproduce this on my mid-2014 MacBook Pro running macOS 10.15.7/Chrome 85 (both latest). There is a very slight shift in the panel when I drag the voltmeter body over it. It is very subtle, and I would not have noticed it if I hadn't been looking for it.

Given @ariel-phet's assessment of wont-fix, I think we can probably close this, but I'll defer to @Denz1994.

**Comment by Denz1994** [comment] 2020-10-15 19:59
This seems like something that we won't fix based on the above comments. Closing this one.

**Closed by Denz1994** 2020-10-15 19:59 UTC
Labels: type:bug, type:wontfix
