### ISSUE TITLE
Cursor gets separated from the green drag arrows

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#76] opened 2016-05-03 17:37 UTC
Clicking in one spot on the green drag arrows, then moving the mouse, I see the mouse gets detached from that point of the arrow.  Perhaps not a big deal, but I'm not sure what is causing this.

**Comment by jessegreenberg** [comment] 2016-05-19 17:24
@samreid I am not sure that I understand the issue, and I can't seem to reproduce.  Is this because the mouse can separate from the arrow when the arrow gets to the max/min values?  It seems to behave much like other draggables in defined bounds, such as a slider thumb in a track.

Or maybe I just haven't observed the issue yet?

**Comment by samreid** [comment] 2016-05-20 03:09
This screencast demonstrates the typical drag behavior, where the mouse "attaches" to a specific location on an object such as the voltmeter.  This works correctly for the voltmeter.  However for the green drag arrows, starting a drag at one site then dragging leads to the mouse "getting away" from that site:

![mouse](https://cloud.githubusercontent.com/assets/679486/15416183/c002664e-1e05-11e6-9b13-91ec1ce62923.gif)

I do not suspect this would be a problem for users, but it seemed odd and I wanted to bring it up in case it was a previously unknown issue, indicative of underlying maintainability problems, nonstandard implementation or other internal issues.

**Comment by jonathanolson** [comment] 2017-01-19 08:53
Looks like this was fixed with the changes to input handling.

**Closed by jonathanolson** 2017-01-19 08:53 UTC
Labels: priority:4-low
