### ISSUE TITLE
Firefox/Edge Performance Issues

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/capacitor-lab-basics#230] opened 2018-01-30 21:59 UTC
Capacitor lab seems to have some performance issues on Firefox and Edge--while fairly minor and unnoticeable usually (hovering around 30 FPS while manipulating the capacitor), if you enable electric fields the FPS and responsiveness of the sim drops significantly while manipulating the capacitor size. Chrome is not affected as badly by the performance issues but I do notice some slowdown with electric fields enabled; barely noticeable but there. It probably isn't terribly high priority or that much of an issue right now. 

Seen on: Edge, Firefox
Discovered in relation to https://github.com/phetsims/QA/issues/86

**Comment by phet-steele** [comment] 2018-02-14 18:36
In https://github.com/phetsims/QA/issues/94#issuecomment-365696448, @ariel-phet said,

>@phet-steele perfromance "as is" is unacceptable on Edge in the situation you showed me. However it seemed like changing the renderer to svg solved the performance issues. It seems the sim should be tested with SVG on edge and firefox, if no issues are found with using that solution, the SVG solution should be used.

**Comment by phet-steele** [comment] 2018-02-14 18:51
I'm testing with https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_all_phet.html?rootRenderer=svg and personally see no performance improvement.

**Comment by phet-steele** [comment] 2018-02-14 23:01
@ariel-phet if you can improve the performance, please comment on your setup.

**Comment by EthanWJohnson** [comment] 2018-02-16 21:12
I looked at edge and firefox with the svg renderer; no performance improvement their either.

**Comment by EthanWJohnson** [comment] 2018-02-16 22:22
Interesting; i'm not seeing the same performance problems on Windows 8 or Windows 7 Firefox and Internet Explorer at all, which means the performance hit from the above situation is limited to Windows 10 and MacOS. Unsure of why that is the case.

**Comment by ariel-phet** [comment] 2018-02-22 01:08
@phet-steele I am currently playing with the sim on my laptop (Win 10 Edge). I have only seen the performance issue once (not switching render, just using the rc link as is). I have not yet been able to repeat what is causing the performance issue. When working well performance is perfectly acceptable in the situation of max plate charge and electric field on.

I am going to continue playing, but it seems like something odd is happening here since the performance is an intermittent issue for me.

**Comment by ariel-phet** [comment] 2018-02-22 01:30
@jonathanolson to reproduce:

First get into the "max charge condition" (full voltage, max plate area, minimum separation) and turn on the electric field
![max charge](https://user-images.githubusercontent.com/4051174/36514926-496e667a-1734-11e8-8a3d-0ff16d87f51c.PNG)

Then disconnect so the capacitor is isolated. Changing the plate separation on Win 10 Edge is pretty bad performance, and changing the plate area becomes pretty much unresponsive.

Win 10 FF performance for me is a bit choppy in this situation but borderline acceptable.

rootRender=svg does not improve performance (I think when I checked that, I must have forgotten to put the capacitor into an "isolated" condition)

**Comment by ariel-phet** [comment] 2018-02-22 01:33
@jonathanolson please note that the published version has these exact same issues, so no new performance issue was introduced. However, since we are likely going to be publishing a Win 10 app, we should try to understand where this performance issue is coming from. Fix it if possible, and/or report to MS.

**Comment by KatieWoe** [comment] 2019-04-11 19:41
https://github.com/phetsims/capacitor-lab-basics/issues/230#issuecomment-367537030 still occurs in dev.7.  There also was a bit of lag in firefox when the light from the bulb shrinks.
![electricfieldslow](https://user-images.githubusercontent.com/41024075/55987758-7371d800-5c5f-11e9-8e43-3c520c22c8f2.gif)
![firefoxstrobelight](https://user-images.githubusercontent.com/41024075/55987760-7371d800-5c5f-11e9-9d27-eea8c1640d4a.gif)

**Comment by KatieWoe** [comment] 2019-04-11 22:43
This happens on IE as well.

**Comment by KatieWoe** [comment] 2019-04-12 16:14
I actually saw some of the delay of the light shrinking in iOS 12 safari as well.

**Comment by KatieWoe** [comment] 2019-04-12 16:59
I will also note that the Electric field lag does not happen on the dev version of edge.

**Comment by KatieWoe** [comment] 2019-04-12 18:47
One more note: I checked the Electric field lag on Mac 10.14 firefox and didn't see it there.

**Comment by ariel-phet** [comment] 2019-04-19 17:15
I looked at this on Win 10 FF, and there is only a slight lack of smoothness these days. Considering the issue is on IE, and the newer version of Edge will fix it, I think we can go ahead and close this issue as improving the performance would likely not be worth the cost. In addition, we have had no complaints from the world with the published version.

**Closed by ariel-phet** 2019-04-19 17:15 UTC
Labels: type:performance
