### ISSUE TITLE
Charge in top plate changes inappropriately

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#256] opened 2019-04-12 19:10 UTC
**Test device:**
Dell and Jordan
**Operating System:**
Win 10 and Mac 10.14
**Browser:**
chrome and safari
**Problem description:**
For https://github.com/phetsims/QA/issues/306, may be connected to https://github.com/phetsims/capacitor-lab-basics/issues/234.  When the sim is paused and discharging, moving the capacitors seems to make the amount of charge change.  This should not be possible, and steping forward one step causes the charge to jump to the correct amount.
**Steps to reproduce:**
1. Charge the plates on the lightbulb screen
2. Turn on top plate charge bar graph
3. Pause the sim
4. Move the wires to connect to the bulb
5. Step forward and observe charge behavior
6. Move plates closer together or further away (while still paused)
7. Observe new charge bar
8. Step forward and observe

**Screenshots:**
![changingchargeamount](https://user-images.githubusercontent.com/41024075/56060419-07a57300-5d24-11e9-9e01-8211bbb80143.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-dev.7/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-dev.7 2019-04-10 22:42:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment] 2019-04-12 23:18
Nice find @KatieWoe!

Since the published version doesn't have a pause button, it is hard to tell if this bug exists there, but it doesn't look like it.

Definitely looks like charge isn't being conserved here @Denz1994. Moving the plates while the sim is paused should never affect the amount of charge. While discharging, the charge on the plates would exponentially decay.

**Comment by Denz1994** [comment] 2019-04-22 14:53
@arouinfar I believe this issue persisted in the published version. You see the change when following the steps without pausing, but it is a lot less apparent.

The top plate charge only updates when the capacitor is connected to the battery. @arouinfar Please double check that this behavior is correct in master.

**Comment by arouinfar** [comment] 2019-04-29 23:08
@Denz1994 master still looks off to me.

When the capacitor is disconnected from the battery, changing its capacitance results in a change in the voltage (Q is conserved and Q = CV). Here, decreasing C results in proportionally increased V.

![ConservedQ](https://user-images.githubusercontent.com/8419308/56932219-18821280-6aa0-11e9-8ff5-53d330f97481.gif)

Similarly, when connected to the bulb, changing C should create an instantaneous change in V. Here, decreasing C from 1.77 pF to 0.35 pF should have increased the voltage from 1.5 V to 7.5 V, resulting in a larger halo. Instead, the voltage remains 1.5 V, and the charge is instead reduced.
![ConservedQ2](https://user-images.githubusercontent.com/8419308/56932220-191aa900-6aa0-11e9-8947-199ea0375e2c.gif)

If you run into any questions, or would like to discuss over Zoom, please let me know.

**Comment by Denz1994** [comment] 2019-04-30 17:40
`this.capacitor.discharge( )` was is responsible for updating the inverse relationship between capacitance and voltage, when the light bulb was connected. This function was being called during `step()` so when the sim was paused this wasn't being handled.

The capacitor now discharges when the plate geometry changes which should maintain conservation of charge. @arouinfar could you confirm in master?

**Comment by arouinfar** [comment] 2019-05-01 02:48
Looks great @Denz1994!

**Comment by KatieWoe** [comment] 2019-05-07 21:31
May be connected to https://github.com/phetsims/capacitor-lab-basics/issues/259.  As such, will leave up to @Denz1994 on whether this is fixed/whether to close

**Comment by Denz1994** [comment] 2019-05-23 09:38
The changes in https://github.com/phetsims/capacitor-lab-basics/issues/259 should not have affected this, though closely related. This issue should be verified by QA to ensure it is resolved.

**Comment by KatieWoe** [comment] 2019-05-24 16:56
This seems to occur under more specific circumstances now.  A bit harder to reproduce now.
1. Go to the light bulb screen
2. Add charge to the plates
3. Select the check box for reading the top plate charge (easier to see change)
4. While battery is still connected change either the area or distance of the plates
5. Pause the sim
6. While paused, switch to the light bulb connections
7. While still paused, move the plates closer/further away or bigger/smaller
8. The instant you do that the amount of charge will change.  It will stay at the same charge with further movement

Removing the ready-for qa label.
![specificcircumstances](https://user-images.githubusercontent.com/41024075/58344308-940e7f80-7e12-11e9-997c-1a8b71aa6970.gif)

**Comment by KatieWoe** [comment] 2019-05-24 18:39
https://github.com/phetsims/QA/issues/321

**Comment by arouinfar** [comment] 2019-05-24 20:27
Great find @KatieWoe.

@Denz1994 it looks like the plate charge isn't getting properly stored/updated on pause.

1. On startup, open Light Bulb screen
2. Turn on Top Plate Charge graph, then charge capacitor. Make a note of the Top Plate Charge value.
3. Pause sim, then change capacitance (e.g. decrease separation). This results in a change in Top Plate Charge, as it should.
4. Move switch to light bulb.
5. Change capacitance (e.g. increase separation). The Top Plate Charge should match the value in step 3, but instead reverts to the Top Plate Charge in step 2.

**Comment by Denz1994** [comment] 2019-06-18 15:16
After much digging, it turns out that capacitor.discharge() should not be used when dragging the plate area and separation arrows. It causes the capacitor to leak voltage and produced a side effect where the charges could be built up to indefinitely when swapping to an open circuit.

The voltage is now explicitly set using Q=V/C when dragged. This prevents charges from being lost and the voltage drops or increases accordingly.

**Comment by KatieWoe** [comment] 2019-06-18 19:47
Not fixed.  Now, you must pause the sim, switch to light bulb, move the plates, and then step through while paused.
![stillchargejumps](https://user-images.githubusercontent.com/41024075/59714777-a8565a00-91cf-11e9-8335-d5871affad88.gif)

**Comment by etwa4650** [comment] 2019-06-18 20:46
https://drive.google.com/open?id=1-8shThGK3r3NfECoiMY9IpNRyc2rRm9q

Some more strange behavior if you pause the sim after switching to the lightbulb, and then move plates closer while paused. Top plate charge will jump back up to what it was before connecting to the lightbulb (0.27 in this video).

**Comment by KatieWoe** [comment] 2019-06-21 16:48
One more oddity here.  When making the plate larger and smaller while discharging the charge jumps up and down.  But I've only seen it so far on IE Win 7.  Wondering if this is due to performance or something with IE.

**Comment by KatieWoe** [comment] 2020-03-02 20:08
In master when doing ES6 Testing. Moving the plates when not connected to the battery or bulb makes all the charge go away when on the light bulb screen. If the plates are close enough together charges come back, but behave as if the plates are connected to the battery.
![comesback](https://user-images.githubusercontent.com/41024075/75713402-f8564d80-5c86-11ea-8839-ee528ac0f129.gif)

**Comment by Denz1994** [comment] 2020-10-14 19:44
Instead of setting the top plate charge when the capacitance changes, the charges are discharged. This bug was introduced when trying to explicitly set the capacitor charge when the plate geometry or separation changes. I've reviewed this briefly with @arouinfar but she will review further in this [RC version](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.4/phet/capacitor-lab-basics_all_phet.html).

**Comment by arouinfar** [comment] 2020-10-14 23:59
@Denz1994 looks good in rc.4

**Comment by loganbraywork** [comment] 2020-10-16 20:56
This still seems to be broken as of https://github.com/phetsims/QA/issues/565. By following the steps laid out in the comment above.

> This seems to occur under more specific circumstances now. A bit harder to reproduce now.
> 
> 1. Go to the light bulb screen
> 2. Add charge to the plates
> 3. Select the check box for reading the top plate charge (easier to see change)
> 4. While battery is still connected change either the area or distance of the plates
> 5. Pause the sim
> 6. While paused, switch to the light bulb connections
> 7. While still paused, move the plates closer/further away or bigger/smaller
> 8. The instant you do that the amount of charge will change.  It will stay at the same charge with further movement
> 
> Edit: It seems that just adjusting the charge with the battery while paused will cause this.
> 
> Removing the ready-for qa label.
> ![specificcircumstances](https://user-images.githubusercontent.com/41024075/58344308-940e7f80-7e12-11e9-997c-1a8b71aa6970.gif)

Currently. using the switch still causes a jump in top plate energy if the sim was paused while the plates were adjusted.
![2020-10-16CapacitorlabbasicsChargeinappropriately](https://user-images.githubusercontent.com/54685448/96307991-c0a2d880-0fbf-11eb-9bcb-c12c1d783f12.gif)

**Comment by Denz1994** [comment] 2020-10-19 16:14
A patch was made to remove explicitly setting the discharge parameters when the geometry changes. This should be handled by discharging. This is more apparent when we can pause because discharging happens during the step. Can you verify this is fixed in this [version](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.6/phet/capacitor-lab-basics_all_phet.html) @loganbraywork?

**Comment by KatieWoe** [comment] 2020-10-20 16:14
It now seems to be back to the original behavior where it changes when the plate is changed consistently. In fact, it seems worse since it doesn't jump back to correct behavior when you play/step forward. I also notice the play and step forward buttons are behind the light from the bulb now, making them almost impossible to use.
![backtobuggy](https://user-images.githubusercontent.com/41024075/96613961-d31d5a80-12bc-11eb-919e-0e9531189d40.gif)

**Comment by arouinfar** [comment] 2020-10-22 02:51
Charge is definitely not being conserved in master. For example:

1. Turn on Top Plate Charge
2. Charge capacitor (voltage irrelevant)
3. Disconnect capacitor, and take note of top plate charge.
4. Change plate separation or area, and the charge changes. This should not happen.

**Comment by KatieWoe** [comment] 2020-11-03 20:22
I'm not always seeing as much as I saw in https://github.com/phetsims/capacitor-lab-basics/issues/256#issuecomment-712965729, and have some trouble reproducing to that degree for some reason. But even so I get a consistent one time jump when I start to move the plates.

**Comment by Denz1994** [comment] 2020-12-17 02:30
The discharge model was simplified in the above commit. Also, the `previousCapacitance` was being changed as a side effect of discharging but used elsewhere (see `updateDischargeParameters`).

The steps in https://github.com/phetsims/capacitor-lab-basics/issues/256#issuecomment-710621089 should be verified by QA.

**Comment by KatieWoe** [comment] 2021-01-14 21:58
Things are looking good in rc.8 so far. Closing for now, but will keep an eye out and reopen if something reappears.

**Comment by CliffordH123** [comment] 2021-03-19 17:20
This has come back for https://github.com/phetsims/QA/issues/616
![plateChargeChange](https://user-images.githubusercontent.com/9455257/111818552-eac93100-88a4-11eb-9b00-2a403a17c9a2.gif)
Steps:
1. Charge plates
2. Pause Sim.
3. Switch plates to bulb
4. Do not un-pause
5. Change Plate distance
6. Observe top plate charge graph change

**Comment by arouinfar** [comment] 2021-03-19 17:35
Good find @CliffordH123. Looks like yet another regression @jonathanolson, so I'm wondering if we should pause/cancel this dev test.

**Comment by jonathanolson** [comment] 2021-04-08 15:18
@KatieWoe I believe this is fixed in master, can you verify?

**Comment by KatieWoe** [comment] 2021-04-12 15:36
Adding this to issues to verify on QA board

**Comment by brooklynlash** [comment] 2021-04-12 18:10
Looks fixed on master, Win10 Chrome.

**Comment by loganbraywork** [comment] 2021-04-14 23:43
This appears fixed as of https://github.com/phetsims/QA/issues/640 on Win 10 Chrome.

**Closed by loganbraywork** 2021-04-14 23:43 UTC
Labels: status:ready-for-qa, type:bug
