### ISSUE TITLE
review use of Animation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/capacitor-lab-basics#252] opened 2019-03-29 15:08 UTC
In https://github.com/phetsims/twixt/issues/18, twixt `MoveTo` and `OpacityTo` were replaced by `Animation`. 

Moving this last bit of work here so that the twixt issue can be closed.

8/28/18 https://github.com/phetsims/twixt/issues/18#issuecomment-415904940:
> Assigning to @jonathanolson to review the replacement in capacitor-lab-basics, to decide whether he'd like to use a different variation of the Animation options, and whether to use stepper: 'timer'. Feel free to close after that review.

**Comment by ariel-phet** [comment] 2019-04-24 19:45
Changing assignment to @Denz1994

**Comment by Denz1994** [comment] 2019-04-30 18:39
The refactors made in commit 3cd145acf943a4df059d288625bb6a862bc197ee where the latest relevant changes to the animation code. Since then, the refactored animation behavior has been tested in [dev test cycle](https://github.com/phetsims/QA/issues/306) and has worked as intended. Closing this issue.

**Closed by Denz1994** 2019-04-30 18:39 UTC
Labels: status:ready-for-review
