### ISSUE TITLE
Current arrows reverse near zero volts

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/capacitor-lab-basics#97] opened 2016-05-19 18:56 UTC
Test device: Schrodinger, Witten

Operating System: Win 8, iOS 9.3.2

Browser: Chrome, Safari

Problem description: If you let the capacitor slowly discharge through the lightbulb, and disconnect it shortly before it reaches zero volts, its voltage may jump directly to zero, and then if connected to the light bulb again, the current arrows will briefly appear pointing in the opposite direction.

Steps to reproduce: Set the capacitor to have a small gap and large area, so it discharges slowly. Give it some small initial voltage from the battery, and use the voltmeter to watch the capacitor's voltage. Discharge the capacitor through the bulb, and note the direction the current arrows point during that time. When the voltage is near but not quite at zero, disconnect the capacitor, around .01V is when I got it to happen. The voltage drops instantly to zero, then connect the capacitor to the bulb again, and the current arrows will briefly point the opposite direction.

Screenshots:
![clb](https://cloud.githubusercontent.com/assets/11947677/15405843/f25f39a4-1dc0-11e6-84cc-5067fce9caa0.gif)

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.20/capacitor-lab-basics_en.html
Version: 1.0.0-dev.20 2016-05-18 14:09:12 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Language: en-US
Window: 1920x921
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9bf8f88c","branch":"master"},"babel":{"sha":"db759b40","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"capacitor-lab-basics":{"sha":"f44dab43","branch":"master"},"chipper":{"sha":"2413d310","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"3931eb76","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"20409355","branch":"master"},"scenery-phet":{"sha":"b77dc7e1","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"6f66368f","branch":"master"},"tandem":{"sha":"29f64233","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

For phetsims/tasks#598

**Comment by andrewadare** [comment] 2016-05-25 15:04
Nice job, that is some thorough testing. This is a pretty marginal case, and I can reproduce it, but not very easily.

The problem is that the current is calculated in [two different ways](https://github.com/phetsims/capacitor-lab-basics/blob/5743bf844c21578325ddadef03e652bd4da1dae6/js/light-bulb/model/LightBulbCircuit.js#L238-L253): V/R when the light bulb is connected, and dQ/dt when it's not. They're not 100% consistent, but that's only noticeable in cases like this one.

Currently (no pun intended), we have a minimum voltage cutoff of 1 mV so the exponential discharge doesn't trickle on forever. That's when the current arrows begin fading out.

The simplest fix I can think of is to start fading the current arrows just a bit sooner than that, so the inconsistency is invisible (or at least visible for less of the time).

**Comment by andrewadare** [comment] 2016-05-25 15:24
421d86ed6a02e9f9a303dbd344e9bfbfafed0045 helps with this issue, but it can still happen. I believe it's a judgment call at this point whether to put in more effort on it.

**Comment by jessegreenberg** [comment] 2016-06-09 17:44
Thanks for looking into this @andrewadare.  We will probably want to close this before the upcoming student testing.

**Closed** 2016-06-09 19:43 UTC
Labels: priority:2-high, type:bug
