### ISSUE TITLE
Current arrows appear while capacitor disconnected

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#16] opened 2015-10-15 21:57 UTC
At times, the current arrows can appear when the battery is disconnected from the capacitor. This can be tricky to reproduce, but one possible way is to:
* Set battery voltage to -1.5V
* Charge the capacitor, and set capacitor area/separation to something in the middle (e.g. 7mm, 300mm^2)
* Disconnect capacitor, and adjust separation and/or plate area

![clb](https://cloud.githubusercontent.com/assets/8419308/10528732/3ef10aac-7355-11e5-8c8d-5647a1a06ca5.gif)

**Comment by jessegreenberg** [comment] 2016-04-08 18:38
There is a chance that #26 will fix this issue, we should handle that first and then see if this is still an issue.

**Comment by jessegreenberg** [comment] 2016-04-08 22:01
#26 did not fix this, but it did elucidate a possible solution.

**Comment by jessegreenberg** [comment] 2016-04-08 22:43
I tried for a few minutes and can no longer reproduce this issue. Tried the steps above in the original comment.

This commit should be cherry picked to the accessibility branch because the issue was observable with keyboard navigation as well. Closing.

**Closed by jessegreenberg** 2016-04-08 22:43 UTC
Labels: type:bug
