### ISSUE TITLE
Ghost lines from diminishing top plate charge

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/capacitor-lab-basics#264] opened 2019-05-08 20:42 UTC
**Test Device**

Bates

**Operating System**

Windows 7

**Browser**

Firefox 66.0.4

**Problem Description**

For https://github.com/phetsims/QA/issues/315. Ghost lines can be seen from diminishing top plate charge. The ghost lines eventually disappear.

**Steps to Reproduce**

1. Check top plate charge checkbox.
2. Charge plates.
3. Flip switch to connect circuit to light.

**Screenshots**

![Ghost-Lines](https://user-images.githubusercontent.com/31285590/57406663-94661400-719e-11e9-9a24-887e623678bd.JPG)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.1/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.1 2019-05-07 18:06:40 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by lmulhall-phet** [comment] 2019-05-08 20:46
Possibly related to https://github.com/phetsims/scenery/issues/810#issue-329210787. Feel free to close if you think this is the case @Denz1994.

**Comment by lmulhall-phet** [comment] 2019-05-08 20:49
Or possibly https://github.com/phetsims/ph-scale-basics/issues/33.

**Comment by Denz1994** [comment] 2019-05-14 15:13
@lmulhall-phet I'm going to close this one as it seems to be related to https://github.com/phetsims/scenery/issues/810.

Just noting, I was able to reproduce a less severe version of this bug on a MacBookPro (macOS Mojave 10.14.3) Firefox 66.0.2 (64-bit).

**Closed by Denz1994** 2019-05-14 15:13 UTC
Labels: type:bug
